/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shanuka
 */
public class Employee_Managment extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Management
     */
    public Employee_Managment() {
        initComponents();
        setID();
        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT EID,`name`,`username` FROM `doctor` where isDeleted='No' order by EID ASC");
            ResultSet rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void setID() {
        int x = 0;

        PreparedStatement pst;
        try {
            pst = db.con().prepareStatement("SELECT count(`EID`) FROM `doctor`");
            ResultSet rs = pst.executeQuery();
            rs.next();
            x = Integer.parseInt(rs.getString(1));
            x = x + 1;
            id.setText(String.valueOf(x));
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setEID(String tb) {
        int x = 0;

        PreparedStatement pst;
        try {
            pst = db.con().prepareStatement("SELECT count(`EID`) FROM " + tb + "");
            ResultSet rs = pst.executeQuery();
            rs.next();
            x = Integer.parseInt(rs.getString(1));
            x = x + 1;
            empid.setText(String.valueOf(x));
        } catch (SQLException ex) {
            Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        specs = new javax.swing.JComboBox();
        usnm = new javax.swing.JTextField();
        docnm = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        dt = new datechooser.beans.DateChooserCombo();
        jLabel17 = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        charge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        tto = new javax.swing.JTextField();
        tfrom = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        totalpat = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        clinictxt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        etel = new javax.swing.JTextField();
        euser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pos = new javax.swing.JComboBox();
        epass2 = new javax.swing.JPasswordField();
        epass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        empid = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        empid1 = new javax.swing.JTextField();
        nm1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        etel1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        euser1 = new javax.swing.JTextField();
        epass1 = new javax.swing.JPasswordField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        epass3 = new javax.swing.JPasswordField();
        male1 = new javax.swing.JRadioButton();
        female1 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        pos3 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        pos2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Specialization     :");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(30, 170, 170, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Date                     :");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(30, 230, 170, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Contact No          :");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(30, 290, 170, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Confirm Pass            :");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(650, 223, 200, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Time                     :");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(30, 350, 160, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("UserName                 :");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(650, 50, 200, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Password                  :");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(650, 133, 200, 40);

        specs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Obstetrics and Gynecology", "Cardioligist", "ENT", "OPD", "Surgeon", "Physiologist", "Psychologist", "Pediatrician", "Ophthalmologist" }));
        specs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                specsItemStateChanged(evt);
            }
        });
        specs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specsActionPerformed(evt);
            }
        });
        jPanel4.add(specs);
        specs.setBounds(200, 170, 280, 40);
        jPanel4.add(usnm);
        usnm.setBounds(850, 50, 280, 40);
        jPanel4.add(docnm);
        docnm.setBounds(200, 110, 280, 40);

        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });
        jPanel4.add(contact);
        contact.setBounds(200, 290, 280, 40);
        jPanel4.add(pass);
        pass.setBounds(850, 130, 280, 40);
        jPanel4.add(dt);
        dt.setBounds(200, 232, 280, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("To :");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(370, 350, 40, 40);
        jPanel4.add(conpass);
        conpass.setBounds(850, 220, 280, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("From :");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(200, 350, 60, 40);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doc ID", "Doctor Name", "USERNAME"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(30, 450, 520, 290);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/30.png"))); // NOI18N
        jButton5.setText("Register");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(900, 300, 230, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.png"))); // NOI18N
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(650, 690, 140, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/29.png"))); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7);
        jButton7.setBounds(990, 690, 140, 50);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/28.png"))); // NOI18N
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(650, 300, 210, 50);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Charge                               :");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(650, 450, 200, 40);

        charge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chargeKeyTyped(evt);
            }
        });
        jPanel4.add(charge);
        charge.setBounds(850, 450, 280, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Doctor Name      :");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(30, 110, 170, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("EID                       :");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(30, 50, 170, 40);

        id.setEditable(false);
        jPanel4.add(id);
        id.setBounds(200, 50, 280, 40);
        jPanel4.add(tto);
        tto.setBounds(370, 390, 110, 30);

        tfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfromActionPerformed(evt);
            }
        });
        jPanel4.add(tfrom);
        tfrom.setBounds(200, 390, 110, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("No of Patients per day     :");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(650, 520, 200, 40);

        totalpat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalpatKeyTyped(evt);
            }
        });
        jPanel4.add(totalpat);
        totalpat.setBounds(850, 520, 280, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Clinic                                   :");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(650, 590, 200, 40);
        jPanel4.add(clinictxt);
        clinictxt.setBounds(850, 590, 280, 40);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("hh:mm");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(500, 390, 50, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/32.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(820, 690, 140, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        jPanel4.add(jLabel24);
        jLabel24.setBounds(0, 10, 1200, 790);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, -10, 1200, 790);

        jTabbedPane1.addTab("Doctor Details", jPanel3);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gender                     :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(170, 520, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Employee Name      :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 120, 190, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Telephone                :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 180, 190, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Position                    :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 240, 190, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Username                :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 300, 190, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Password                 :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(170, 370, 190, 40);

        nm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(nm);
        nm.setBounds(370, 120, 340, 40);

        etel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etelKeyTyped(evt);
            }
        });
        jPanel2.add(etel);
        etel.setBounds(370, 180, 340, 40);

        euser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(euser);
        euser.setBounds(370, 300, 340, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Confirm Pass           :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 440, 190, 40);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        male.setText("Male");
        jPanel2.add(male);
        male.setBounds(370, 520, 140, 40);

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        female.setText("Female");
        jPanel2.add(female);
        female.setBounds(570, 520, 140, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/30.png"))); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(470, 610, 240, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.png"))); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(960, 50, 200, 50);

        pos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "receptionist", "laboratorian" }));
        pos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                posItemStateChanged(evt);
            }
        });
        pos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posMouseClicked(evt);
            }
        });
        pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posActionPerformed(evt);
            }
        });
        jPanel2.add(pos);
        pos.setBounds(370, 240, 340, 40);

        epass2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(epass2);
        epass2.setBounds(370, 440, 340, 40);

        epass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(epass);
        epass.setBounds(370, 370, 340, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Employee ID            :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 50, 190, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/29.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(170, 610, 220, 50);

        empid.setEditable(false);
        empid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(empid);
        empid.setBounds(370, 50, 340, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        jPanel2.add(jLabel25);
        jLabel25.setBounds(0, 0, 1200, 780);

        jTabbedPane1.addTab("Employee", jPanel2);

        jPanel5.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Employee ID :");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(40, 40, 141, 40);

        empid1.setEditable(false);
        jPanel5.add(empid1);
        empid1.setBounds(240, 40, 340, 40);
        jPanel5.add(nm1);
        nm1.setBounds(240, 110, 340, 40);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Employee Name :");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(40, 110, 141, 40);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Telephone :");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(40, 170, 141, 40);

        etel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etel1KeyTyped(evt);
            }
        });
        jPanel5.add(etel1);
        etel1.setBounds(240, 170, 340, 40);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Position :");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(40, 230, 141, 40);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Username :");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(40, 290, 141, 40);
        jPanel5.add(euser1);
        euser1.setBounds(240, 290, 340, 40);
        jPanel5.add(epass1);
        epass1.setBounds(240, 360, 340, 40);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Password :");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(40, 360, 141, 40);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Confirm Pass :");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(40, 430, 141, 40);
        jPanel5.add(epass3);
        epass3.setBounds(240, 430, 340, 40);

        buttonGroup1.add(male1);
        male1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male1.setText("Male");
        jPanel5.add(male1);
        male1.setBounds(270, 510, 93, 25);

        buttonGroup1.add(female1);
        female1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        female1.setText("Female");
        jPanel5.add(female1);
        female1.setBounds(460, 510, 69, 25);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Gender :");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(40, 500, 70, 40);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Emp Id", "Emp Name", "tel"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(680, 90, 452, 402);

        pos3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "receptionist", "laboratorian" }));
        pos3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pos3ItemStateChanged(evt);
            }
        });
        pos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos3MouseClicked(evt);
            }
        });
        pos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos3ActionPerformed(evt);
            }
        });
        jPanel5.add(pos3);
        pos3.setBounds(900, 30, 190, 40);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Position :");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(800, 30, 80, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/28.png"))); // NOI18N
        jButton9.setText("Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(440, 630, 140, 50);

        pos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos2ActionPerformed(evt);
            }
        });
        jPanel5.add(pos2);
        pos2.setBounds(240, 230, 340, 40);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.png"))); // NOI18N
        jButton10.setText("HOME");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(70, 630, 140, 50);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        jPanel5.add(jLabel28);
        jLabel28.setBounds(0, 0, 1200, 780);

        jTabbedPane1.addTab("Employee Update", jPanel5);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1200, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posActionPerformed
        setEID(pos.getSelectedItem().toString());
    }//GEN-LAST:event_posActionPerformed

    private void posMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posMouseClicked
        setEID(pos.getSelectedItem().toString());
    }//GEN-LAST:event_posMouseClicked

    private void posItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_posItemStateChanged

    }//GEN-LAST:event_posItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!nm.getText().equals("")) {
            PreparedStatement pst;
            try {
                pst = db.con().prepareStatement("UPDATE " + pos.getSelectedItem().toString() + " SET isDeleted='Yes' WHERE `name`='" + nm.getText() + "'");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Success!");
                empid.setText("");
                nm.setText("");
                
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Employee");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = nm.getText();
        String position = pos.getSelectedItem().toString();
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        String tel = etel.getText();
        String gender = "";
        if (male.isSelected()) {
            gender = "male";
        } else {
            gender = "female";
        }

        String user = euser.getText();
        String pass1 = String.valueOf(epass.getPassword());
        String pass2 = String.valueOf(epass2.getPassword());

        String x = empid.getText();

        if (!(name.equals("") || position.equals("") || tel.equals("") || gender.equals("") || user.equals("") || pass1.equals("") || pass2.equals(""))) {

            if (pass1.equals(pass2)) {
                try {
                    PreparedStatement ps = db.con().prepareStatement("INSERT INTO " + position + "(`EID`, `name`, `tel`, `sex`, `username`, `pass`, `isDeleted`, `date`) VALUES(?,?,?,?,?,?,?,?)");
                    ps.setString(1, x);
                    ps.setString(2, name);
                    ps.setString(3, tel);
                    ps.setString(4, gender);
                    ps.setString(5, user);
                    ps.setString(6, pass1);
                    ps.setString(7, "No");

                    ps.setString(8, today);

                    ps.execute();
                    JOptionPane.showMessageDialog(null, "Registration Successfull");

                    empid.setText("");
                    nm.setText("");

                    etel.setText("");
                    male.setSelected(false);
                    female.setSelected(false);
                    euser.setText("");
                    epass.setText("");
                    epass2.setText("");
                    setEID(pos.getSelectedItem().toString());
                } catch (SQLException ex) {
                    Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password mismatch");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the relevant fields");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfromActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        String sp = specs.getSelectedItem().toString();
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        String tel = contact.getText();
        String from = tfrom.getText();
        String to = tto.getText();
        String user = usnm.getText();
        String pass1 = String.valueOf(pass.getPassword());
        String pass2 = String.valueOf(conpass.getPassword());
        String chrge = charge.getText();
        String x = id.getText();
        String pat = totalpat.getText();
        String clinic = clinictxt.getText();
        if (!(sp.equals("") || pat.equals("") || clinic.equals("") || tel.equals("") || from.equals("") || to.equals("") || user.equals("") || pass1.equals("") || pass2.equals("") || chrge.equals(""))) {

            if (pass1.equals(pass2)) {
                PreparedStatement pst;
                try {
                    pst = db.con().prepareStatement("UPDATE `doctor` SET totalPatients='" + pat + "',`clinic`='" + clinic + "',`specialization`='" + sp + "',`tel`='" + tel + "',`startTime`='" + from + "',`endTime`='" + to + "',`charge`='" + chrge + "',`username`='" + user + "',`pass`='" + pass1 + "' WHERE EID='" + x + "'");
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update Successfull");
                    setID();
                    docnm.setText("");
                    specs.setSelectedItem("");
                    contact.setText("");
                    tfrom.setText("");
                    tto.setText("");
                    usnm.setText("");
                    pass.setText("");
                    conpass.setText("");
                    charge.setText("");
                    dt.setText("");
                    totalpat.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "password mismatch");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the form");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "select a doctor");
        } else {
            PreparedStatement pst;
            try {
                pst = db.con().prepareStatement("Update `doctor` set isDeleted='Yes' where EID='" + id.getText() + "'");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Success!");
                setID();
                docnm.setText("");
                specs.setSelectedItem("");
                contact.setText("");
                tfrom.setText("");
                tto.setText("");
                usnm.setText("");
                pass.setText("");
                conpass.setText("");
                charge.setText("");
                dt.setText("");
                totalpat.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT EID,`name`,`username` FROM `doctor` where isDeleted='No' order by EID ASC");
            ResultSet rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name = docnm.getText();
        String sp = specs.getSelectedItem().toString();
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        String tel = contact.getText();
        String from = tfrom.getText();
        String to = tto.getText();
        String user = usnm.getText();
        String pass1 = String.valueOf(pass.getPassword());
        String pass2 = String.valueOf(conpass.getPassword());
        String chrge = charge.getText();
        String x = id.getText();
        String pat = totalpat.getText();
        String clinic = clinictxt.getText();

        if (!(name.equals("") || clinic.equals("") || sp.equals("") || tel.equals("") || from.equals("") || to.equals("") || user.equals("") || pass1.equals("") || pass2.equals("") || chrge.equals("") || pat.equals(""))) {

            if (pass1.equals(pass2)) {
                try {
                    PreparedStatement ps = db.con().prepareStatement("INSERT INTO `doctor`(`EID`, `name`, `specialization`, `clinic`, `date`, `tel`, `startTime`, `endTime`, `charge`, `username`, `pass`, `isDeleted`, `totalPatients`, `assigned`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, x);
                    ps.setString(2, name);
                    ps.setString(3, sp);
                    ps.setString(4, clinic);

                    ps.setString(5, today);
                    ps.setString(6, tel);
                    ps.setString(7, from);
                    ps.setString(8, to);
                    ps.setString(9, chrge);
                    ps.setString(10, user);
                    ps.setString(11, pass1);

                    ps.setString(12, "No");
                    ps.setString(13, pat);
                    ps.setString(14, "0");
                    ps.execute();
                    JOptionPane.showMessageDialog(null, "Registration Successfull");
                    setID();

                    docnm.setText("");
                    specs.setSelectedItem("");
                    contact.setText("");
                    tfrom.setText("");
                    tto.setText("");
                    usnm.setText("");
                    pass.setText("");
                    conpass.setText("");
                    charge.setText("");
                    dt.setText("");
                    totalpat.setText("");

                } catch (SQLException ex) {
                    Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password mismatch");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the relevant fields");
        }

        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT EID,`name`,`username` FROM `doctor` where isDeleted='No' order by EID ASC");
            ResultSet rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        try {
            String doc = String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 0));
            PreparedStatement pst = db.con().prepareStatement("SELECT * FROM `doctor` where EID='" + doc + "'");
            ResultSet rs = pst.executeQuery();
            rs.next();
            id.setText(rs.getString(1));
            docnm.setText(rs.getString(2));
            specs.setSelectedItem(rs.getString(3));
            contact.setText(rs.getString(6));
            tfrom.setText(rs.getString(7));
            tto.setText(rs.getString(8));
            usnm.setText(rs.getString(10));
            pass.setText(rs.getString(11));
            conpass.setText(rs.getString(11));
            charge.setText(rs.getString(9));
            dt.setText(rs.getString(5));
            totalpat.setText(rs.getString(13));

        } catch (SQLException ex) {
            Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void specsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specsActionPerformed
        clinictxt.setText(specs.getSelectedItem().toString());
    }//GEN-LAST:event_specsActionPerformed

    private void specsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_specsItemStateChanged
        clinictxt.setText(specs.getSelectedItem().toString());
    }//GEN-LAST:event_specsItemStateChanged

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        try {
            String emp = String.valueOf(jTable3.getValueAt(jTable3.getSelectedRow(), 0));
            PreparedStatement pst = db.con().prepareStatement("SELECT * FROM " + pos3.getSelectedItem().toString() + " where EID='" + emp + "'");
            ResultSet rs = pst.executeQuery();
            rs.next();
            empid1.setText(rs.getString(1));
            nm1.setText(rs.getString(2));

            pos2.setText(pos3.getSelectedItem().toString());

            etel1.setText(rs.getString(3));
            euser1.setText(rs.getString(5));
            epass1.setText(rs.getString(6));
            epass3.setText(rs.getString(6));
            male1.setEnabled(false);
            female1.setEnabled(false);

        } catch (SQLException ex) {
            Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void pos3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pos3ItemStateChanged
        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT EID,`name`,tel FROM " + pos3.getSelectedItem().toString() + " where isDeleted='No'");
            ResultSet rs = pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_pos3ItemStateChanged

    private void pos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos3MouseClicked

    }//GEN-LAST:event_pos3MouseClicked

    private void pos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String name = nm1.getText();
        String position = pos2.getText();

        String tel = etel1.getText();

        String user = euser1.getText();
        String pass1 = String.valueOf(epass1.getPassword());
        String pass2 = String.valueOf(epass3.getPassword());

        String x = empid1.getText();
        if (!(name.equals("") || position.equals("") || tel.equals("") || user.equals("") || pass1.equals("") || pass2.equals(""))) {

            if (pass1.equals(pass2)) {
                PreparedStatement pst;
                try {
                    pst = db.con().prepareStatement("UPDATE " + position + " SET `name`='" + name + "',`tel`='" + tel + "',`username`='" + user + "',`pass`='" + pass1 + "' WHERE  `EID`='" + x + "'");
                    pst.execute();
                    System.out.println(x + " " + position);
                    JOptionPane.showMessageDialog(null, "Update Successfull");

                    empid1.setText("");
                    nm1.setText("");
                    etel1.setText("");
                    pos2.setText("");
                    euser1.setText("");
                    epass1.setText("");
                    epass3.setText("");
                    male1.setSelected(false);
                    female1.setSelected(false);

                } catch (SQLException ex) {
                    Logger.getLogger(Employee_Managment.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password mismatch");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the form");
        }
        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT EID,`name`,tel FROM " + pos3.getSelectedItem().toString() + " where isDeleted='No'");
            ResultSet rs = pst.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void pos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos2ActionPerformed

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char c = evt.getKeyChar();

        String text = contact.getText();

        if (c == 43 && text.indexOf('+') != -1) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }

        if (text.length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_contactKeyTyped

    private void chargeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chargeKeyTyped
        char c = evt.getKeyChar();

        if (c == 43) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }


    }//GEN-LAST:event_chargeKeyTyped

    private void totalpatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalpatKeyTyped
        char c = evt.getKeyChar();

        if (c == 43) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }


    }//GEN-LAST:event_totalpatKeyTyped

    private void etelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etelKeyTyped
        char c = evt.getKeyChar();

        String text = etel.getText();

        if (c == 43 && text.indexOf('+') != -1) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }

        if (text.length() > 12) {
            evt.consume();
        }
    }//GEN-LAST:event_etelKeyTyped

    private void etel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etel1KeyTyped
        char c = evt.getKeyChar();

        String text = etel1.getText();

        if (c == 43 && text.indexOf('+') != -1) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }

        if (text.length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_etel1KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        docnm.setText("");
        contact.setText("");
        tfrom.setText("");
        tto.setText("");
        usnm.setText("");
        pass.setText("");
        conpass.setText("");
        charge.setText("");
        totalpat.setText("");
        clinictxt.setText("");
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Managment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Managment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField charge;
    private javax.swing.JTextField clinictxt;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField docnm;
    private datechooser.beans.DateChooserCombo dt;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField empid1;
    private javax.swing.JPasswordField epass;
    private javax.swing.JPasswordField epass1;
    private javax.swing.JPasswordField epass2;
    private javax.swing.JPasswordField epass3;
    private javax.swing.JTextField etel;
    private javax.swing.JTextField etel1;
    private javax.swing.JTextField euser;
    private javax.swing.JTextField euser1;
    private javax.swing.JRadioButton female;
    private javax.swing.JRadioButton female1;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton male1;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField nm1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JComboBox pos;
    private javax.swing.JTextField pos2;
    private javax.swing.JComboBox pos3;
    private javax.swing.JComboBox specs;
    private javax.swing.JTextField tfrom;
    private javax.swing.JTextField totalpat;
    private javax.swing.JTextField tto;
    private javax.swing.JTextField usnm;
    // End of variables declaration//GEN-END:variables
}
