/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shanuka
 */
public class Laboratory extends javax.swing.JFrame {

    /**
     * Creates new form Laboratory
     */
    public Laboratory() {
        initComponents();

        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT count(`invoiceNo`) FROM `do`");
            ResultSet rs = pst.executeQuery();
            rs.next();
            invo.setText(String.valueOf(Integer.parseInt(rs.getString(1)) + 1));
        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT `patid`,first_name,last_name FROM `patient`");
            ResultSet rs;
            rs = pst.executeQuery();
            while (rs.next()) {
                pat.addItem(rs.getString(1) + " " + rs.getString(2) + " " + rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            PreparedStatement pst;
            pst = db.con().prepareStatement("SELECT `name` FROM `checkups`");
            ResultSet rs;
            rs = pst.executeQuery();
            while (rs.next()) {
                tset.addItem(rs.getString(1));
            }

        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        tset = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        pat = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        invo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1230, 850));
        setMinimumSize(new java.awt.Dimension(1230, 850));
        setPreferredSize(new java.awt.Dimension(1230, 850));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Checkup details :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 190, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Invoice No          :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 110, 160, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Patient            :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(760, 110, 140, 40);

        total.setEditable(false);
        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total);
        total.setBounds(880, 630, 210, 40);

        tset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsetActionPerformed(evt);
            }
        });
        jPanel1.add(tset);
        tset.setBounds(520, 110, 190, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Test  :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(460, 110, 60, 40);

        pat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(pat);
        pat.setBounds(910, 110, 180, 40);

        des.setColumns(20);
        des.setRows(5);
        jScrollPane1.setViewportView(des);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 190, 860, 120);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chechup Name", "Description", "Charge"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(60, 430, 1030, 160);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/33.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(760, 700, 330, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.png"))); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 700, 240, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/32.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(430, 700, 230, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total           :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(760, 630, 120, 40);

        invo.setEditable(false);
        invo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(invo);
        invo.setBounds(230, 110, 190, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/31.png"))); // NOI18N
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(230, 350, 120, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1240, 800);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int size = 0;
        double x = 0;
        try {
            PreparedStatement pst = db.con().prepareStatement("SELECT `cost` FROM `checkups` WHERE `name`='" + tset.getSelectedItem().toString() + "'");
            ResultSet rs = pst.executeQuery();
            rs.next();
            String charge = rs.getString(1);

            tb.addRow(new Object[]{tset.getSelectedItem().toString(), des.getText(), charge});
            size = jTable1.getRowCount();
            for (int i = 0; i < size; i++) {
                x = x + Double.parseDouble(tb.getValueAt(i, 2).toString());
            }
            total.setText(String.valueOf(x));

        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }
        des.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed
    public void print() {
        PreparedStatement ps1;
        String patient = null;
        String patient1 = pat.getSelectedItem().toString();
        String[] pt = patient1.split(" ");
        patient = pt[1] + " " + pt[2];

        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("lab report " + invo.getText() + " - " + today + ".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filePath = dialog.getSelectedFile().getPath();

            try {

                Document myDocument = new Document();

                PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
                myDocument.open();
                myWriter.setPageEvent(new MyPdfPageEventHelper("report1.png"));
                myDocument.add(new Paragraph("\n\n\n\n\n\n"));
                myDocument.add(new Paragraph("CHECKUPS", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("Invoice No : " + invo.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));
                myDocument.add(new Paragraph("Patient ID : " + pt[0], FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("Name : " + patient, FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));

                PdfPTable table = new PdfPTable(3);

                table.setWidthPercentage(100);
                float[] columnWidths = new float[]{8, 5, 5};
                table.setWidths(columnWidths);

                myDocument.add(new Paragraph(today));
                myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("\n"));
                table.addCell(new PdfPCell(new Paragraph("Checkup Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("Description", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("Charge(Rs.)", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));

                for (int i = 0; i < jTable1.getRowCount(); i++) {

                    table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 0).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                    table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 1).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                    table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 2).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));

                }

                myDocument.add(table);
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("Total cost : Rs. " + total.getText()));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));

                myDocument.close();

                JOptionPane.showMessageDialog(null, "Report was successfully generated");

            } catch (DocumentException ex) {
                Logger.getLogger(Prescription.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Prescription.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String patient1 = pat.getSelectedItem().toString();
        String[] pt = patient1.split(" ");
        String patient = pt[0];
        String inv = invo.getText();
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        if (patient.equals("")) {
            JOptionPane.showMessageDialog(null, "Select the patient");
        } else {
            try {
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    PreparedStatement pst = db.con().prepareStatement("INSERT INTO `do`(`checkupName`, `patid`, `invoiceNo`, `date`, `description`,total) VALUES(?,?,?,?,?,?)");
                    pst.setString(1, jTable1.getValueAt(i, 0).toString());
                    pst.setString(2, patient);
                    pst.setString(3, inv);
                    pst.setString(4, today);
                    pst.setString(5, jTable1.getValueAt(i, 1).toString());
                    pst.setString(6, total.getText());
                    pst.execute();
                    print();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        tb.setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void tsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea des;
    private javax.swing.JTextField invo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox pat;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox tset;
    // End of variables declaration//GEN-END:variables
}
