/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Denam
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form pat
     */
    public Patient() {
        initComponents();
        setId();
        settable();
        settable2();
        try {
            PreparedStatement pst = db.con().prepareStatement("SELECT clinic FROM `doctor`");
            ResultSet rs;
            rs = pst.executeQuery();
            while (rs.next()) {
                clinic.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void settable() {
        try {
            PreparedStatement pst;
            ResultSet rs;
            pst = db.con().prepareStatement("SELECT `patid`, `first_name`, `last_name`,`gender`, `telephone` FROM `patient`");

            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void settable2() {
        try {
            PreparedStatement pst;
            ResultSet rs;
            pst = db.con().prepareStatement("SELECT `patid`, `first_name`, `last_name`,`gender`, `telephone` FROM `patient`");

            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setId() {
        try {
            PreparedStatement ps = db.con().prepareStatement("select count(patid) from patient");
            ResultSet rs = ps.executeQuery();
            int id = 0;
            while (rs.next()) {
                id = Integer.parseInt(rs.getString(1));
            }
            id = id + 1;
            pIdField.setText("p" + String.valueOf(id));
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        clinic = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        search1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pIdField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Gender1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pAddressField = new javax.swing.JTextArea();
        pPhoneField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        fmale = new javax.swing.JRadioButton();
        pAgeField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pNameField1 = new javax.swing.JTextField();
        pNameField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1230, 845));
        setMinimumSize(new java.awt.Dimension(1230, 845));
        setPreferredSize(new java.awt.Dimension(1230, 845));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Clinic                   :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(83, 557, 160, 40);

        clinic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clinic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clinicItemStateChanged(evt);
            }
        });
        jPanel1.add(clinic);
        clinic.setBounds(246, 560, 190, 40);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "ID" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(250, 70, 130, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Search by         :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(90, 70, 150, 50);

        search1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search1KeyReleased(evt);
            }
        });
        jPanel1.add(search1);
        search1.setBounds(481, 70, 200, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/34.png"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(740, 70, 140, 49);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Last Name", "Gender", "Telephone"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(90, 220, 950, 170);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/36.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(838, 470, 200, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.png"))); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(840, 550, 200, 50);

        pat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patKeyReleased(evt);
            }
        });
        jPanel1.add(pat);
        pat.setBounds(250, 470, 180, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Patient Id            :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(83, 468, 170, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Service Charge   :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(80, 650, 160, 40);

        ser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serKeyTyped(evt);
            }
        });
        jPanel1.add(ser);
        ser.setBounds(245, 650, 190, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Available:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 560, 90, 40);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(560, 558, 48, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 770);

        jTabbedPane1.addTab("Assign Doctor", jPanel1);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Id:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 80, 116, 31);

        pIdField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIdFieldActionPerformed(evt);
            }
        });
        jPanel3.add(pIdField);
        pIdField.setBounds(180, 80, 229, 50);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "ID" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(730, 80, 100, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Search by  :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(620, 80, 110, 50);

        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel3.add(search);
        search.setBounds(850, 80, 170, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/34.png"))); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(1030, 80, 140, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "First Name", "Last Name", "Gender", "Telephone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(622, 170, 550, 300);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/32.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(950, 670, 220, 60);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/28.png"))); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(440, 270, 160, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/30.png"))); // NOI18N
        jButton5.setText("Register");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(440, 170, 160, 60);

        Gender1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Gender1.setText("Address:");
        jPanel3.add(Gender1);
        Gender1.setBounds(40, 562, 116, 60);

        pAddressField.setColumns(20);
        pAddressField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pAddressField.setRows(5);
        jScrollPane3.setViewportView(pAddressField);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(180, 580, 229, 151);

        pPhoneField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPhoneFieldActionPerformed(evt);
            }
        });
        pPhoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pPhoneFieldKeyTyped(evt);
            }
        });
        jPanel3.add(pPhoneField);
        pPhoneField.setBounds(180, 486, 229, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Telephone:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(40, 486, 116, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Gender:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(40, 410, 128, 36);

        male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        male.setText("Male");
        jPanel3.add(male);
        male.setBounds(180, 410, 100, 40);

        fmale.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fmale.setText("Female");
        jPanel3.add(fmale);
        fmale.setBounds(310, 410, 100, 40);

        pAgeField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pAgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAgeFieldActionPerformed(evt);
            }
        });
        pAgeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pAgeFieldKeyTyped(evt);
            }
        });
        jPanel3.add(pAgeField);
        pAgeField.setBounds(180, 326, 229, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Age:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(40, 326, 116, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Last Name:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(40, 236, 116, 50);

        pNameField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameField1ActionPerformed(evt);
            }
        });
        jPanel3.add(pNameField1);
        pNameField1.setBounds(180, 236, 229, 50);

        pNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameFieldActionPerformed(evt);
            }
        });
        jPanel3.add(pNameField);
        pNameField.setBounds(180, 160, 229, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("First Name:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(40, 160, 116, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Reg Date    :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(620, 530, 130, 50);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jTextField2);
        jTextField2.setBounds(750, 530, 240, 50);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.png"))); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(620, 670, 220, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 1200, 770);

        jTabbedPane1.addTab("Patient Management", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIdFieldActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        PreparedStatement pst;
        ResultSet rs;

        if (search.getText().equals("")) {
            settable();
        }
        try {
            pst = db.con().prepareStatement("SELECT `patid`, `first_name`, `last_name`,`gender`, `telephone` FROM `patient` WHERE `first_name` like'%" + search.getText() + "%' OR patid like'%" + search.getText() + "%'");

            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            TableModel model1 = jTable1.getModel();

            PreparedStatement pst;
            ResultSet rs;

            pst = db.con().prepareStatement("SELECT * FROM `patient` where patid='" + model1.getValueAt(jTable1.getSelectedRow(), 0) + "'");

            rs = pst.executeQuery();

            while (rs.next()) {
                pIdField.setText(rs.getString(1));
                pNameField.setText(rs.getString(2));
                pNameField1.setText(rs.getString(3));
                pAgeField.setText(rs.getString(4));
                if (rs.getString(5).equals("male")) {
                    male.setSelected(true);
                    fmale.setSelected(false);
                } else {
                    fmale.setSelected(true);
                    male.setSelected(false);
                }
                pPhoneField.setText(rs.getString(7));
                pAddressField.setText(rs.getString(8));
                jTextField2.setText(rs.getString(6));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        pNameField.setText("");
        pNameField1.setText("");
        pAgeField.setText("");

        pPhoneField.setText("");
        pAddressField.setText("");
        male.setSelected(false);
        fmale.setSelected(false);
        setId();
        settable();
        settable2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            PreparedStatement pst;
            ResultSet rs;
            String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());

            pst = db.con().prepareStatement("UPDATE `patient` SET `first_name`='" + pNameField.getText() + "',`last_name`='" + pNameField1.getText() + "',`age`='" + pAgeField.getText() + "',`date`='" + date + "',`telephone`='" + pPhoneField.getText() + "',`address`='" + pAddressField.getText() + "' WHERE `patid`='" + pIdField.getText() + "'");

            pst.execute();
            JOptionPane.showMessageDialog(null, "Update success");
            pNameField.setText("");
            pNameField1.setText("");
            pAgeField.setText("");

            pPhoneField.setText("");
            pAddressField.setText("");
            male.setSelected(false);
            fmale.setSelected(false);
            setId();
            settable();
            settable2();
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            PreparedStatement prp;

            String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
            String id = pIdField.getText();
            String name = pNameField.getText();
            String lname = pNameField1.getText();

            String gender;
            if (male.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }
            String address = pAddressField.getText();
            String phone = pPhoneField.getText();

            String sql = "INSERT INTO `patient`(`patid`, `first_name`, `last_name`, `age`, `gender`, `date`, `telephone`, `address`)  values (?,?,?,?,?,?,?,?)";

            if (pAgeField.equals("") || name.equals("") || lname.equals("") || gender.equals("") || address.equals("") || phone.equals("")) {
                JOptionPane.showMessageDialog(null, "Pls fill the form!");
            } else {
                int age = Integer.parseInt(pAgeField.getText());
                prp = db.con().prepareStatement(sql);
                prp.setString(1, id);
                prp.setString(2, name);
                prp.setString(3, lname);
                prp.setInt(4, age);
                prp.setString(5, gender);
                prp.setString(6, date);
                prp.setString(7, phone);
                prp.setString(8, address);
                prp.execute();
                JOptionPane.showMessageDialog(null, "Data Saved");

                pNameField.setText("");
                pNameField1.setText("");
                pAgeField.setText("");

                pPhoneField.setText("");
                pAddressField.setText("");
                male.setSelected(false);
                fmale.setSelected(false);

                setId();
                settable();
                settable2();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPhoneFieldActionPerformed

    private void pAgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAgeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pAgeFieldActionPerformed

    private void pNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameField1ActionPerformed

    private void pNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameFieldActionPerformed

    private void search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search1KeyReleased
        PreparedStatement pst;
        ResultSet rs;
        if (search1.getText().equals("")) {
            settable2();
        }
        try {
            pst = db.con().prepareStatement("SELECT `patid`, `first_name`, `last_name`,`gender`, `telephone` FROM `patient` WHERE `first_name` like'%" + search1.getText() + "%' OR patid like'%" + search1.getText() + "%'");

            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_search1KeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        String val = (String) jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0);
        pat.setText(val);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement pst;
        ResultSet rs;

        if (search.getText().equals("")) {
            settable();
        }
        try {
            pst = db.con().prepareStatement("SELECT `patid`, `first_name`, `last_name`,`gender`, `telephone` FROM `patient` WHERE `first_name` like'%" + search.getText() + "%' OR patid like'%" + search.getText() + "%'");

            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        settable();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PreparedStatement pst;
        ResultSet rs;

        if (search1.getText().equals("")) {
            settable2();
        }
        try {
            pst = db.con().prepareStatement("SELECT `patid`, `first_name`, `last_name`,`gender`, `telephone` FROM `patient` WHERE `first_name` like'%" + search1.getText() + "%' OR patid like'%" + search1.getText() + "%'");

            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton6ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (ser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill Service Charge");
        } else {
            String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());

            PreparedStatement pst;
            ResultSet rs;

            try {
                pst = db.con().prepareStatement("INSERT INTO `assign` VALUES (?,?,?,?,?,?)");
                pst.setString(1, clinic.getSelectedItem().toString());
                pst.setString(2, pat.getText());
                pst.setString(3, ser.getText());
                pst.setString(4, date);
                pst.setString(5, "No");
                pst.setString(6, "No");
                pst.execute();

                PreparedStatement ps = db.con().prepareStatement("update patient set frequent=frequent+1 where patid='" + pat.getText() + "'");
                ps.execute();

                PreparedStatement ps1 = db.con().prepareStatement("update doctor set assigned=(assigned+1) where clinic='" + clinic.getSelectedItem().toString() + "'");
                ps1.execute();
                setavailable();
                JOptionPane.showMessageDialog(null, "Done!");

                clinic.setSelectedIndex(0);
                pat.setText("");
                ser.setText("");
                search1.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void patKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_patKeyReleased

    private void serKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_serKeyReleased

    private void clinicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clinicItemStateChanged
        setavailable();
    }//GEN-LAST:event_clinicItemStateChanged

    public void setavailable() {
        try {
            PreparedStatement ps = db.con().prepareStatement("select totalPatients,assigned from doctor where clinic='" + clinic.getSelectedItem().toString() + "'");
            ResultSet rs = ps.executeQuery();

            int x = 0, y = 0;

            while (rs.next()) {
                x = rs.getInt(1);
                y = rs.getInt(2);
            }

            if (x > y) {
                jTextField1.setText(String.valueOf(x - y));
                jButton1.setEnabled(true);
            } else {
                jTextField1.setText("0");
                jButton1.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        search.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pAgeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pAgeFieldKeyTyped
        char c = evt.getKeyChar();

        if (c == 43) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }

    }//GEN-LAST:event_pAgeFieldKeyTyped

    private void pPhoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pPhoneFieldKeyTyped
        char c = evt.getKeyChar();

        String text = pPhoneField.getText();

        if (c == 43 && text.indexOf('+') != -1) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }

        if (text.length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_pPhoneFieldKeyTyped

    private void serKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serKeyTyped
        char c = evt.getKeyChar();

        if (c == 43) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }

    }//GEN-LAST:event_serKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender1;
    private javax.swing.JComboBox<String> clinic;
    private javax.swing.JRadioButton fmale;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextArea pAddressField;
    private javax.swing.JTextField pAgeField;
    private javax.swing.JTextField pIdField;
    private javax.swing.JTextField pNameField;
    private javax.swing.JTextField pNameField1;
    private javax.swing.JTextField pPhoneField;
    private javax.swing.JTextField pat;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JTextField ser;
    // End of variables declaration//GEN-END:variables
}
