/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shanuka
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form Payements
     */
    public Payments() {

        initComponents();
        invo();
    }

    public void invo() {
        try {
            PreparedStatement ps = db.con().prepareStatement("select count(patid) from assign");
            ResultSet rs = ps.executeQuery();
            rs.next();
            jTextField3.setText("INV-" + rs.getString(1));
        } catch (SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        doc = new javax.swing.JTextField();
        clinic = new javax.swing.JTextField();
        docchrge = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        scharge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1220, 850));
        setMinimumSize(new java.awt.Dimension(1220, 850));
        setPreferredSize(new java.awt.Dimension(1220, 850));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Payement");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Total                      :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 640, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Search Name       :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(600, 80, 180, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Invoice No.                   :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 140, 220, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("First Name                    :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Last Name                    :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 260, 220, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tel.                                :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 320, 220, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address                         :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 380, 220, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Doctor                          :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 470, 220, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Clinic                             :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 530, 220, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Doctor Charge             :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 590, 220, 40);
        jPanel1.add(total);
        total.setBounds(790, 640, 190, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(780, 80, 230, 50);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(240, 140, 260, 40);
        jPanel1.add(fname);
        fname.setBounds(240, 200, 260, 40);
        jPanel1.add(lname);
        lname.setBounds(240, 260, 260, 40);

        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        jPanel1.add(tel);
        tel.setBounds(240, 320, 260, 40);
        jPanel1.add(addr);
        addr.setBounds(240, 380, 260, 70);
        jPanel1.add(doc);
        doc.setBounds(240, 470, 260, 40);
        jPanel1.add(clinic);
        clinic.setBounds(240, 530, 260, 40);
        jPanel1.add(docchrge);
        docchrge.setBounds(240, 590, 260, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.png"))); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 720, 190, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/32.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(300, 720, 200, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/34.png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1040, 80, 140, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/35.png"))); // NOI18N
        jButton1.setText("Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1020, 610, 160, 70);

        jTextField12.setEditable(false);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField12);
        jTextField12.setBounds(790, 560, 60, 40);
        jPanel1.add(scharge);
        scharge.setBounds(240, 650, 260, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Loyalty Discount  :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(610, 560, 180, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Patient ID                     :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 80, 220, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("%");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(850, 560, 30, 40);
        jPanel1.add(pat);
        pat.setBounds(240, 80, 260, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Service Charge            :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 650, 220, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Address", "Tel"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(600, 200, 580, 240);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1210, 800);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1210, 820);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        if (pat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls select the patient first");
        } else {
            try {
                PreparedStatement ps = db.con().prepareStatement("update assign set finished='Yes' where patid='" + pat.getText() + "' and date='" + today + "' and clinic='" + clinic.getText() + "'");
                ps.execute();
                print();
            } catch (SQLException ex) {
                Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
            }

            invo();

            pat.setText("");
            fname.setText("");
            lname.setText("");
            tel.setText("");
            addr.setText("");
            doc.setText("");
            clinic.setText("");
            docchrge.setText("");
            scharge.setText("");
            total.setText("");
            jTextField12.setText("");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public void print() {

        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("payment invo of " + pat.getText() + " - " + today + ".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filePath = dialog.getSelectedFile().getPath();

            try {

                Document myDocument = new Document();

                PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
                myDocument.open();
                myWriter.setPageEvent(new MyPdfPageEventHelper("report1.png"));
                myDocument.add(new Paragraph("\n\n\n\n\n\n"));
                Paragraph head = new Paragraph("PAYMENT INVOICE", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD));
                head.setAlignment(Element.ALIGN_CENTER);
                myDocument.add(head);
                myDocument.add(new Paragraph("\n\n"));
                myDocument.add(new Paragraph("Invoice No : " + jTextField3.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));

                Paragraph pdate = new Paragraph(today, FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD));
                pdate.setAlignment(Element.ALIGN_LEFT);
                myDocument.add(pdate);
                myDocument.add(new Paragraph("Name : " + fname.getText() + " " + lname.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));
                myDocument.add(new Paragraph("Tel : " + tel.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("\n"));
               
                myDocument.add(new Paragraph("Doctor Name : " + doc.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));
                myDocument.add(new Paragraph("Clinic Name : " + clinic.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));

                myDocument.add(new Paragraph("Doctor charge : Rs. " + docchrge.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));

                myDocument.add(new Paragraph("Service Charge : Rs. " + scharge.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));

                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("\n"));
                myDocument.add(new Paragraph("\n"));

                myDocument.add(new Paragraph("\n"));

                myDocument.add(new Paragraph("Discount : Rs. " + jTextField12.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));

                myDocument.add(new Paragraph("Total : Rs. " + total.getText(), FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.PLAIN)));

                myDocument.close();

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MedicalCeti.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(MedicalCeti.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Report was successfully generated");
        }
    }

    public void settable2() {
        try {
            PreparedStatement pst;
            ResultSet rs;
            pst = db.con().prepareStatement("SELECT patient.patid,patient.`first_name`, patient.`last_name`, patient.`telephone`,assign.clinic FROM `patient` inner join assign on patient.patid=assign.patid where assign.done='Yes' and assign.finished='No'");

            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PreparedStatement pst;
        ResultSet rs;
        if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the patient ID or name");
        } else {

            try {
                pst = db.con().prepareStatement("SELECT patient.patid, patient.`first_name`, patient.`last_name`, patient.`telephone`,assign.clinic FROM `patient` inner join assign on patient.patid=assign.patid WHERE assign.finished='No' and patient.first_name like'%" + jTextField2.getText() + "%' OR patient.last_name like'%" + jTextField2.getText() + "%'");

                rs = pst.executeQuery();

                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

            } catch (SQLException ex) {
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        PreparedStatement pst;
        ResultSet rs;

        try {
            pst = db.con().prepareStatement("SELECT patient.patid, patient.`first_name`, patient.`last_name`, patient.`telephone`,assign.clinic FROM `patient` inner join assign on patient.patid=assign.patid WHERE assign.finished='No' and patient.first_name like'%" + jTextField2.getText() + "%' OR patient.last_name like'%" + jTextField2.getText() + "%'");

            rs = pst.executeQuery();

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try {
            String val = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            String cl = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4);

            PreparedStatement pst = db.con().prepareStatement("SELECT patient.`patid`, patient.`first_name`, patient.`last_name`, patient.`telephone`,patient.address, assign.clinic,(select doctor.name from doctor where clinic='" + cl + "') ,  (select doctor.charge from doctor inner join assign on doctor.clinic=assign.clinic where assign.clinic='" + cl + "' and assign.patid='" + val + "' and assign.finished='No') ,assign.serviceCharge,patient.frequent FROM `patient` inner join assign on patient.patid=assign.patid WHERE patient.`patid` = '" + val + "' and assign.clinic='" + cl + "'");
            ResultSet rs = pst.executeQuery();
            int fre = 0;
            while (rs.next()) {
                pat.setText(rs.getString(1));
                fname.setText(rs.getString(2));
                lname.setText(rs.getString(3));
                tel.setText(rs.getString(4));
                addr.setText(rs.getString(5));
                doc.setText(rs.getString(7));
                clinic.setText(rs.getString(6));
                docchrge.setText(rs.getString(8));
                scharge.setText(rs.getString(9));

                fre = rs.getInt(10);
            }

            if (fre == 0) {
                jTextField12.setText("0");
            } else if (fre > 0 && fre <= 5) {
                jTextField12.setText("0");
            } else if (fre > 5 && fre <= 10) {
                jTextField12.setText("5");
            } else if (fre > 10) {
                jTextField12.setText("10");
            }
            String sc = "";
            if (scharge.getText().equals("")) {
                sc = "0.0";
            } else {
                sc = scharge.getText();
            }
            Float dch = Float.parseFloat(docchrge.getText());
            Float sch = Float.parseFloat(sc);
            int loya = (100 - Integer.parseInt(jTextField12.getText()));
            Float ttal = dch + ((sch * loya) / 100);

            total.setText(String.valueOf(ttal));

        } catch (SQLException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        invo();
        pat.setText("");
        fname.setText("");
        lname.setText("");
        tel.setText("");
        addr.setText("");
        doc.setText("");
        clinic.setText("");
        docchrge.setText("");
        scharge.setText("");
        total.setText("");
        jTextField12.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
    char c = evt.getKeyChar();

        String text = tel.getText();

        if (c == 43 && text.indexOf('+') != -1) {
            evt.consume();
        }
        if (!Character.isDigit(c) && c != 8 && c != 43) {
            evt.consume();
        }

        if (text.length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_telKeyTyped

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JTextField clinic;
    private javax.swing.JTextField doc;
    private javax.swing.JTextField docchrge;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField pat;
    private javax.swing.JTextField scharge;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
